- name: Deploy a web application
  hosts: all
  become: True
  become_user: root
  tasks:
    - name: Install EPEL repo from repository
      yum:
        name: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
        state: present
        disable_gpg_check: True
      when:
       - ansible_distribution == "RedHat"
       - ansible_distribution_major_version == "8"

    - name: Install all required dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "python36"
        - "python36-devel"


    - name: Install MySQL database
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "mysql-server"
        - "mysql-devel"

    - name: create MySQL configuration file
      copy:
        content: |
          [client]
          user=root
          password="@targ8et"
        dest: "/etc/.my.cnf"

    - name: MySQL bind configuration
      blockinfile:
        state: present
        insertafter: EOF
        dest: /etc/my.cnf.d/mysql-server.cnf
        content: |
          bind-address=0.0.0.0

    - name: Start MySQL Service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install mysql-python package
      yum:
        name: python3-mysql
        state: present

    - name: Install pip
      yum:
        name: python3-pip
        state: present

    - name: Install required Python libraries
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - "flask"
        - "flask-mysql"

    - name: Create Application Database
      mysql_db:
        name: employee_db
        state: present

    - name: Create Database user
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Copy source code
      copy:
        src: app.py
        dest: /opt/app.py

    - name: Start web server
      shell: FLASK_APP=/opt/app.py nohup /usr/local/bin/flask run --host=0.0.0.0&
